const mainColors = {
  red1: '#EF2B51',
  blue1: '#6360AA',
  white1: '#FFFFFF',
  white2: '#E5E5E5',
  black1: '#000000',
  black2: '#454A67',
  gray1: '#7D8797',
  gray2: '#E9E9E9',
  gray3: '#EDEEF0',
  gray4: '#B1B7C2',
  orange1: '#F48C1E',
  yellow1: '#FFCC1E',
  green1: '#7FC151',
};

export const colors = {
  primary: mainColors.blue1,
  secondary: mainColors.red1,
  // tertiary: mainColors.blue1,
  white1: mainColors.white1,
  white2: mainColors.white1,
  black1: mainColors.black1,
  black2: mainColors.black2,
  gray1: mainColors.gray1,
  gray2: mainColors.gray2,
  gray3: mainColors.gray3,
  gray4: mainColors.gray4,
  orange1: mainColors.orange1,
  yellow1: mainColors.yellow1,
  green1: mainColors.green1,
  text: {
    primary: mainColors.blue1,
    secondary: mainColors.red1,
  },
  loadingBackground: mainColors.black1,
  errorMessage: mainColors.red1,
};
